Repository volcano-sh/website, pull requests merged in 2021-08, with the labels that each got.

#112 add boyun logo
  content/en/home/supporter.md
  content/zh/home/supporter.md
  static/img/logo_boyun.png
  static/img/logo_caicloud.png
Labels: kind/feature, approved, size/S, kind/documentation, lgtm, retest-not-required-docs-only

#113 add blog leinao os
  .gitignore
  content/en/blog/leinao-en.md
  content/en/blog/paddlepaddle-en.md
  content/en/blog/ruitian-en.md
  content/zh/blog/leinao-cloud-os.md
  content/zh/blog/paddlepaddle.md
  content/zh/blog/ruitian.md
  static/img/leinao-1.png
  static/img/leinao-10.png
  static/img/leinao-11.png
  static/img/leinao-12.png
  static/img/leinao-13.png
  static/img/leinao-2.png
  static/img/leinao-3.png
  static/img/leinao-4.png
  static/img/leinao-5.png
  static/img/leinao-6.png
  static/img/leinao-7.png
  static/img/leinao-8.png
  static/img/leinao-9.png
  static/img/leinao-en1.png
  static/img/leinao-en10.png
  static/img/leinao-en11.png
  static/img/leinao-en12.png
  static/img/leinao-en13.png
  static/img/leinao-en14.png
  static/img/leinao-en2.png
  static/img/leinao-en3.png
  static/img/leinao-en4.png
  static/img/leinao-en5.png
  static/img/leinao-en6.png
  static/img/leinao-en7.png
  static/img/leinao-en8.png
  static/img/leinao-en9.png
  static/img/ruitian2.png
  static/img/ruitian3.png
Labels: kind/feature, approved, kind/cleanup, kind/documentation, kind/design, lgtm, size/XXL

#114 fix the style of blogs
  content/en/blog/Quick-Start-Volcano.md
  content/en/blog/kube-batch-startup.md
  content/en/blog/leinao-en.md
  content/en/blog/paddlepaddle-en.md
  content/en/blog/ruitian-en.md
  content/zh/blog/Quick-Start-Volcano.md
  content/zh/blog/kube-batch-startup.md
  content/zh/blog/leinao-cloud-os.md
  content/zh/blog/paddlepaddle.md
  content/zh/blog/ruitian.md
Labels: approved, size/L, lgtm, retest-not-required-docs-only

#118 add Xiaohongshu Blog
  content/en/blog/xiaohongshu-en.md
  content/zh/blog/xiaohongshu.md
  static/img/xiaohongshu-1.png
  static/img/xiaohongshu-10.png
  static/img/xiaohongshu-11.png
  static/img/xiaohongshu-2.png
  static/img/xiaohongshu-3.png
  static/img/xiaohongshu-4.png
  static/img/xiaohongshu-5.png
  static/img/xiaohongshu-6.png
  static/img/xiaohongshu-7.png
  static/img/xiaohongshu-8.png
  static/img/xiaohongshu-9.png
  static/img/xiaohongshu-en1.png
  static/img/xiaohongshu-en10.png
  static/img/xiaohongshu-en11.png
  static/img/xiaohongshu-en2.png
  static/img/xiaohongshu-en3.png
  static/img/xiaohongshu-en4.png
  static/img/xiaohongshu-en5.png
  static/img/xiaohongshu-en6.png
  static/img/xiaohongshu-en7.png
  static/img/xiaohongshu-en8.png
  static/img/xiaohongshu-en9.png
Labels: approved, size/L, kind/documentation, lgtm, retest-not-required-docs-only

#117 add hpc Blog
  content/en/blog/hpc-en.md
  content/zh/blog/hpc.md
  static/img/hpc-1.png
  static/img/hpc-10.png
  static/img/hpc-2.png
  static/img/hpc-3.png
  static/img/hpc-4.png
  static/img/hpc-5.png
  static/img/hpc-6.png
  static/img/hpc-7.png
  static/img/hpc-8.png
  static/img/hpc-9.png
  static/img/hpc-en3.png
  static/img/hpc-en4.png
  static/img/hpc-en5.png
  static/img/hpc-en6.png
  static/img/hpc-en7.png
Labels: approved, kind/documentation, lgtm, size/XL, retest-not-required-docs-only

#119 add ruitian blog
  content/en/blog/ruitian2-en.md
  content/zh/blog/ruitian2.md
  static/img/ruitian2-1.png
  static/img/ruitian2-10.png
  static/img/ruitian2-11.png
  static/img/ruitian2-12.png
  static/img/ruitian2-13.png
  static/img/ruitian2-14.png
  static/img/ruitian2-15.png
  static/img/ruitian2-16.png
  static/img/ruitian2-17.png
  static/img/ruitian2-18.png
  static/img/ruitian2-19.png
  static/img/ruitian2-2.png
  static/img/ruitian2-3.png
  static/img/ruitian2-4.png
  static/img/ruitian2-5.png
  static/img/ruitian2-6.png
  static/img/ruitian2-7.png
  static/img/ruitian2-8.png
  static/img/ruitian2-9.png
  static/img/ruitian2-en2.png
Labels: kind/bug, kind/feature, approved, kind/cleanup, kind/documentation, kind/design, lgtm, size/XL, retest-not-required-docs-only
