Repository volcano-sh/website, pull requests merged in 2022-07, with the labels that each got.

#247 update logo to svg
  assets/css/custom.css
  config/_default/params.toml
  static/img/volcano_logo.svg
Labels: approved, size/XS, lgtm

#249 update favicons
  static/img/favicons/android-chrome-192x192.png
  static/img/favicons/android-chrome-512x512.png
  static/img/favicons/apple-touch-icon.png
  static/img/favicons/browserconfig.xml
  static/img/favicons/favicon-16x16.png
  static/img/favicons/favicon-32x32.png
  static/img/favicons/favicon.ico
  static/img/favicons/mstile-144x144.png
  static/img/favicons/mstile-150x150.png
  static/img/favicons/mstile-310x150.png
  static/img/favicons/mstile-310x310.png
  static/img/favicons/mstile-70x70.png
  static/img/favicons/safari-pinned-tab.svg
  static/img/favicons/site.webmanifest
Labels: approved, size/S, lgtm

#251 update user icon to svg
  assets/css/custom.css
  content/en/blog/Quick-Start-Volcano.md
  layouts/_default/list.html
  layouts/partials/blog_metadata.html
  static/img/icon_user.svg
  themes/academic/layouts/partials/li_compact.html
Labels: approved, size/S, lgtm

#255 repaired How to contributing link
  README.md
Labels: kind/bug, kind/feature, approved, size/XS, kind/cleanup, kind/documentation, kind/design, lgtm, retest-not-required-docs-only

#257 Update the way to install vcctl
  content/en/docs/cli.md
  content/zh/docs/cli.md
Labels: approved, size/XS, lgtm, retest-not-required-docs-only

#258 update icon data to svg
  layouts/partials/blog_metadata.html
  static/img/icon_data.svg
Labels: approved, size/XS, lgtm

#261 update time icon to svg
  content/en/talk/kubecon-barcelona-2019/index.md
  content/zh/talk/kubecon-barcelona-2019/index.md
  static/img/icon_time.svg
  themes/academic/layouts/partials/li_compact.html
  themes/academic/layouts/partials/li_compact_talk.html
Labels: approved, size/XS, lgtm

#265 fix blog card on mobile
  assets/css/custom.css
  layouts/_default/list.html
Labels: approved, size/S, lgtm

#267 Accessibility add iframe title
  content/en/blog/Quick-Start-Volcano.md
  content/zh/blog/Quick-Start-Volcano.md
  themes/academic/layouts/shortcodes/gdocs.html
Labels: approved, size/XS, lgtm

#270 [typo] Update queue.md
  doc/concepts/queue.md
Labels: approved, size/XS, lgtm, retest-not-required-docs-only
