Repository volcano-sh/website, pull requests merged in 2022-08, with the labels that each got.

#271 fix icon
  layouts/partials/page_header.html
Labels: approved, size/XS, lgtm

#273 add svg favicon
  layouts/partials/favicons.html
  static/img/favicons/favicon.png
  static/img/favicons/favicon.svg
Labels: approved, size/M, lgtm

#275 min svg
  static/img/favicons/favicon.svg
Labels: approved, size/M, lgtm, retest-not-required-docs-only

#277 refactor css
  assets/css/custom.css
Labels: approved, size/L, lgtm

#280 add arhell as a reviewers
  OWNERS
Labels: approved, size/XS, lgtm, retest-not-required-docs-only

#281 Fix website installation
  content/en/docs/installation.md
  content/zh/docs/installation.md
  doc/quickstart.md
Labels: kind/bug, kind/feature, approved, kind/cleanup, size/S, kind/documentation, kind/design, lgtm, retest-not-required-docs-only

#279 refactor js
  assets/js/custom.js
Labels: approved, size/XS, lgtm
