Repository volcano-sh/website, pull requests merged in 2022-06, with the labels that each got.

#227 update readme hugo install
  README.md
Labels: approved, size/XS, lgtm, retest-not-required-docs-only

#229 update supporter links
  content/en/home/supporter.md
Labels: approved, size/XS, lgtm, retest-not-required-docs-only

#233 add svg slack icon
  config/_default/languages.toml
  config/_default/menus.toml
  static/img/icon_slack.svg
Labels: approved, size/XS, kind/design, lgtm

#235 update docs arrow (ui)
  themes/academic/layouts/partials/docs_sidebar.html
Labels: approved, size/XS, lgtm

#238 fix typo in cli page
  content/en/docs/cli.md
  content/zh/docs/cli.md
Labels: kind/bug, kind/feature, approved, size/XS, kind/cleanup, kind/documentation, kind/design, lgtm, retest-not-required-docs-only

#239 fix user page
  assets/css/custom.css
Labels: approved, size/XS, lgtm

#241 add css cursor on cards
  layouts/partials/widgets/featured.html
Labels: approved, size/XS, lgtm

#243 Accessibility add alt to image
  layouts/partials/page_header.html
Labels: approved, size/XS, lgtm

#245 fix border on tablet
  assets/css/custom.css
Labels: approved, size/XS, lgtm
