Repository volcano-sh/website, pull requests merged in 2022-03, with the labels that each got.

#152 Accessibility update links
  themes/academic/layouts/partials/widgets/about.html
Labels: approved, size/XS, lgtm

#154 Accessibility add alt to img
  themes/academic/layouts/partials/widgets/about.html
Labels: approved, size/XS, lgtm

#158 fix home slider on mobile
  assets/css/custom.css
  themes/academic/layouts/partials/widgets/slider.html
Labels: approved, size/S, kind/design, lgtm

#156 Accessibility add link name
  themes/academic/layouts/partials/navbar.html
Labels: approved, size/XS, lgtm

#160 fix slider item on tablet & mobile
  themes/academic/layouts/partials/widgets/slider.html
Labels: approved, size/S, lgtm

#162 Accessibility update social icons
  themes/academic/layouts/partials/share.html
Labels: approved, size/XS, lgtm

#164 Accessibility add alt to image
  layouts/partials/blog_metadata.html
Labels: approved, size/XS, lgtm

#166 Accessibility update social icons
  layouts/partials/blog_author.html
Labels: approved, size/XS, lgtm

#168 Accessibility add alt to img
  layouts/partials/blog_author.html
Labels: approved, size/XS, lgtm

#170 update copyright
  config/_default/config.toml
Labels: approved, size/XS, lgtm

#176 Add note for specific version volcano installation (Install with YAML files)
  content/en/docs/installation.md
  content/zh/docs/installation.md
Labels: approved, size/XS, lgtm, retest-not-required-docs-only

#177 Accessibility add link name
  themes/academic/layouts/partials/search.html
Labels: approved, size/XS, lgtm

#179 update & add favicons
  layouts/partials/header.html
Labels: approved, size/L, lgtm

#181 fix tag label
  assets/css/custom.css
Labels: approved, size/XS, lgtm
