Repository volcano-sh/website, pull requests merged in 2025-02, with the labels that each got.

#340 fix dropdown styles
  assets/css/custom.css
Labels: approved, size/XS

#349 Fixed #342 Non-Clickable Buttons
  assets/css/custom.css
Labels: kind/bug, approved, size/XS, lgtm

#341 Fix a typo mistake in colocation doc.
  content/zh/docs/colocation.md
Labels: approved, size/XS, kind/documentation, lgtm, retest-not-required-docs-only

#345 Added search query functionality without page redirection
  themes/academic/layouts/partials/navbar.html
Labels: approved, size/L, lgtm

#346 Add v1.11.0 blog
  content/en/blog/Volcano-1.11.0-release.md
  content/zh/blog/Volcano-1.11.0-release.md
Labels: approved, kind/documentation, lgtm, size/XL, retest-not-required-docs-only

#356 fix redundant space of dropdown
  assets/css/custom.css
  themes/academic/layouts/partials/navbar.html
Labels: approved, size/M, lgtm

#357 Adjusted Top Alignment in Mobile View #353
  assets/css/custom.css
Labels: approved, size/XS, lgtm

#360 Extra space removal
  themes/academic/layouts/partials/widgets/about.html
Labels: approved, size/XS, lgtm

#367 fix: slack link on contribution page
  content/en/docs/contribution.md
  themes/academic/layouts/partials/widgets/about.html
Labels: kind/bug, approved, size/XS, kind/cleanup, lgtm
