Repository volcano-sh/website, pull requests merged in 2025-01, with the labels that each got.

#331 Add Key Features Introduction and update existed doc
  config/_default/languages.toml
  config/_default/menus.toml
  content/en/docs/hierarchical_queue.md
  content/en/docs/queue.md
  content/en/docs/queue_resource_management.md
  content/en/docs/unified_scheduling.md
  content/zh/docs/hierarchical_queue.md
  content/zh/docs/queue.md
  content/zh/docs/queue_resource_management.md
  content/zh/docs/unified_scheduling.md
  static/img/hierarchical-queue-example.png
  themes/academic/assets/js/academic.js
  themes/academic/layouts/partials/css/academic.css
  themes/academic/layouts/partials/footer.html
Labels: approved, kind/documentation, lgtm, size/XXL

#334 update current year
  config/_default/config.toml
  layouts/partials/footer_section.html
Labels: approved, size/XS, lgtm

#335 fix english queue doc
  content/en/docs/queue.md
Labels: approved, size/XS, kind/documentation, lgtm, retest-not-required-docs-only

#336 Add colocation and descheduler doc
  content/en/docs/colocation.md
  content/en/docs/descheduler.md
  content/zh/docs/colocation.md
  content/zh/docs/descheduler.md
  static/img/colocation/architecture.png
  static/img/colocation/cpu-burst1-EN.png
  static/img/colocation/cpu-burst1.png
  static/img/colocation/cpu-burst2-EN.png
  static/img/colocation/cpu-burst2.png
  static/img/colocation/network.png
  static/img/colocation/oversubscription.png
  static/img/colocation/oversubscription_EN.png
  static/img/colocation/watermark.png
  static/img/descheduler/descheduler-CN.svg
  static/img/descheduler/descheduler_EN.svg
Labels: approved, kind/documentation, lgtm, size/XXL, retest-not-required-docs-only

#332 Update home page and introduction
  config/_default/languages.toml
  config/_default/menus.toml
  content/en/author/volcano/_index.md
  content/en/docs/_index.md
  content/en/docs/contribution.md
  content/en/docs/v1-10-0/contribution.md
  content/en/docs/v1-7-0/contribution.md
  content/en/docs/v1-8-2/contribution.md
  content/en/docs/v1-9-0/contribution.md
  content/en/home/home_slider.md
  content/en/home/required.md
  content/zh/author/volcano/_index.md
  content/zh/docs/_index.md
  content/zh/docs/contribution.md
  content/zh/docs/v1-10-0/contribution.md
  content/zh/docs/v1-7-0/contribution.md
  content/zh/docs/v1-8-2/contribution.md
  content/zh/docs/v1-9-0/contribution.md
  content/zh/home/home_slider.md
  content/zh/home/required.md
  static/img/ray_logo.png
Labels: approved, size/L, kind/documentation, lgtm

#337 Add network topology and multi cluster scheduling doc
  content/en/docs/colocation.md
  content/en/docs/descheduler.md
  content/en/docs/hierarchical_queue.md
  content/en/docs/multi_cluster_scheduling.md
  content/en/docs/network_topology_aware_scheduling.md
  content/en/docs/queue_resource_management.md
  content/en/docs/unified_scheduling.md
  content/zh/docs/colocation.md
  content/zh/docs/descheduler.md
  content/zh/docs/hierarchical_queue.md
  content/zh/docs/multi_cluster_scheduling.md
  content/zh/docs/network_topology_aware_scheduling.md
  content/zh/docs/queue_resource_management.md
  content/zh/docs/unified_scheduling.md
  static/img/multi-cluster/volcano_global_design.svg
  static/img/network-topology/hypernode-example.png
Labels: approved, kind/documentation, lgtm, size/XL, retest-not-required-docs-only

#338 Update home page style and update some docs
  assets/css/custom.css
  config/_default/languages.toml
  config/_default/menus.toml
  content/en/author/volcano/_index.md
  content/en/docs/actions.md
  content/en/docs/network_topology_aware_scheduling.md
  content/en/docs/queue_resource_management.md
  content/en/home/required.md
  content/en/home/supporter.md
  content/en/home/talks.md
  content/zh/author/volcano/_index.md
  content/zh/docs/actions.md
  content/zh/docs/multi_cluster_scheduling.md
  content/zh/docs/network_topology_aware_scheduling.md
  content/zh/home/required.md
  content/zh/home/supporter.md
  content/zh/home/talks.md
  static/img/logo_360.png
  static/img/logo_bilibili.png
  themes/academic/layouts/partials/widgets/about.html
Labels: approved, kind/documentation, lgtm, size/XL
