Repository volcano-sh/website, pull requests merged in 2025-06, with the labels that each got.

#382 Update network topology aware scheduling doc
  content/en/docs/network_topology_aware_scheduling.md
  content/zh/docs/network_topology_aware_scheduling.md
Labels: approved, size/L, kind/documentation, lgtm, retest-not-required-docs-only

#383 add blogpost and report for 2025 security audit
  content/en/blog/volcano-2025-security-audit.md
  static/reports/Ada-Logics-Volcano-Security-Audit-2025.pdf
Labels: approved, size/M, lgtm

#393 Add kubecon China 2025 iflytek win the case study doc
  content/en/blog/iflytek_case_study.md
  content/zh/blog/iflytek_case_study.md
  static/img/kubecon/iflytek.jpeg
Labels: approved, size/L, kind/documentation, lgtm

#395 Update gpu virtulization doc in v1.11.0
  content/en/docs/_index.md
  content/en/docs/gpu_virtualization.md
  content/en/docs/v1-11-0/_index.md
  content/en/docs/v1-11-0/gpu_virtualization.md
  content/zh/docs/_index.md
  content/zh/docs/gpu_virtualization.md
  content/zh/docs/v1-11-0/_index.md
  content/zh/docs/v1-11-0/gpu_virtualization.md
  static/img/gpu-virtualization/hard_limit.jpg
  static/img/gpu-virtualization/vgpu_device_plugin_metrics.png
Labels: approved, size/L, kind/documentation, lgtm
